// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: MRI2

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Image1;
lv_obj_t *ui_mbft;
// CUSTOM VARIABLES


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t *ui_Screen2;
lv_obj_t *ui_Image3;
void ui_event_mccb( lv_event_t * e);
lv_obj_t *ui_mccb;
void ui_event_rccb( lv_event_t * e);
lv_obj_t *ui_rccb;
void ui_event_pccb( lv_event_t * e);
lv_obj_t *ui_pccb;
void ui_event_pqcb( lv_event_t * e);
lv_obj_t *ui_pqcb;
void ui_event_pfcb( lv_event_t * e);
lv_obj_t *ui_pfcb;
lv_obj_t *ui_dbta;
lv_obj_t *ui_Label48;
void ui_event_dbb( lv_event_t * e);
lv_obj_t *ui_dbb;
void ui_event_sccb( lv_event_t * e);
lv_obj_t *ui_sccb;
lv_obj_t *ui_Label44;
lv_obj_t *ui_Label47;
lv_obj_t *ui_Label49;
lv_obj_t *ui_Label50;
lv_obj_t *ui_Label51;
lv_obj_t *ui_Spinner2;
void ui_event_mbub( lv_event_t * e);
lv_obj_t *ui_mbub;
void ui_event_dbub( lv_event_t * e);
lv_obj_t *ui_dbub;
lv_obj_t *ui_Label52;
lv_obj_t *ui_Label55;
// CUSTOM VARIABLES


// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
lv_obj_t *ui_Screen3;
lv_obj_t *ui_Image2;
void ui_event_mpb( lv_event_t * e);
lv_obj_t *ui_mpb;
lv_obj_t *ui_Label2;
void ui_event_rupb( lv_event_t * e);
lv_obj_t *ui_rupb;
lv_obj_t *ui_Label3;
void ui_event_rdpb( lv_event_t * e);
lv_obj_t *ui_rdpb;
lv_obj_t *ui_Label4;
void ui_event_dpb( lv_event_t * e);
lv_obj_t *ui_dpb;
lv_obj_t *ui_Label1;
// CUSTOM VARIABLES


// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
lv_obj_t *ui_Screen4;
void ui_event_axrb( lv_event_t * e);
lv_obj_t *ui_axrb;
void ui_event_t1rb( lv_event_t * e);
lv_obj_t *ui_t1rb;
void ui_event_t2rb( lv_event_t * e);
lv_obj_t *ui_t2rb;
void ui_event_mainrb( lv_event_t * e);
lv_obj_t *ui_mainrb;
void ui_event_rdarb( lv_event_t * e);
lv_obj_t *ui_rdarb;
lv_obj_t *ui_mvd;
lv_obj_t *ui_mcd;
void ui_event_msvd( lv_event_t * e);
lv_obj_t *ui_msvd;
void ui_event_mscd( lv_event_t * e);
lv_obj_t *ui_mscd;
void ui_event_Button4( lv_event_t * e);
lv_obj_t *ui_Button4;
void ui_event_Button5( lv_event_t * e);
lv_obj_t *ui_Button5;
void ui_event_Button6( lv_event_t * e);
lv_obj_t *ui_Button6;
void ui_event_Button7( lv_event_t * e);
lv_obj_t *ui_Button7;
void ui_event_mpsob( lv_event_t * e);
lv_obj_t *ui_mpsob;
void ui_event_Checkbox6( lv_event_t * e);
lv_obj_t *ui_Checkbox6;
void ui_event_mbb( lv_event_t * e);
lv_obj_t *ui_mbb;
lv_obj_t *ui_attvd;
lv_obj_t *ui_rdavd;
lv_obj_t *ui_mainvd;
lv_obj_t *ui_Label8;
lv_obj_t *ui_Label9;
lv_obj_t *ui_Label10;
lv_obj_t *ui_Label11;
lv_obj_t *ui_Label12;
lv_obj_t *ui_Label13;
lv_obj_t *ui_Label14;
lv_obj_t *ui_Label15;
lv_obj_t *ui_Label16;
lv_obj_t *ui_Label17;
lv_obj_t *ui_Label43;
// CUSTOM VARIABLES


// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
lv_obj_t *ui_Screen5;
lv_obj_t *ui_utcd;
void ui_event_Button11( lv_event_t * e);
lv_obj_t *ui_Button11;
void ui_event_Button10( lv_event_t * e);
lv_obj_t *ui_Button10;
lv_obj_t *ui_uid;
void ui_event_usb( lv_event_t * e);
lv_obj_t *ui_usb;
void ui_event_ucb( lv_event_t * e);
lv_obj_t *ui_ucb;
void ui_event_rurcb( lv_event_t * e);
lv_obj_t *ui_rurcb;
lv_obj_t *ui_Label5;
lv_obj_t *ui_Label18;
lv_obj_t *ui_Label20;
lv_obj_t *ui_Label21;
lv_obj_t *ui_Label37;
void ui_event_rupcb( lv_event_t * e);
lv_obj_t *ui_rupcb;
lv_obj_t *ui_Label42;
lv_obj_t *ui_Spinner3;
lv_obj_t *ui_Checkbox7;
// CUSTOM VARIABLES


// SCREEN: ui_Screen6
void ui_Screen6_screen_init(void);
lv_obj_t *ui_Screen6;
lv_obj_t *ui_ocd;
lv_obj_t *ui_ovd;
lv_obj_t *ui_otd;
void ui_event_ossb( lv_event_t * e);
lv_obj_t *ui_ossb;
void ui_event_oob( lv_event_t * e);
lv_obj_t *ui_oob;
lv_obj_t *ui_opb;
lv_obj_t *ui_ota;
lv_obj_t *ui_oattvd;
lv_obj_t *ui_omainvd;
lv_obj_t *ui_mainof;
lv_obj_t *ui_axof;
lv_obj_t *ui_Label22;
lv_obj_t *ui_Label19;
lv_obj_t *ui_Label23;
lv_obj_t *ui_Label24;
lv_obj_t *ui_Label25;
lv_obj_t *ui_Label26;
lv_obj_t *ui_Label27;
void ui_event_rub( lv_event_t * e);
lv_obj_t *ui_rub;
lv_obj_t *ui_tovd;
// CUSTOM VARIABLES


// SCREEN: ui_Screen7
void ui_Screen7_screen_init(void);
lv_obj_t *ui_Screen7;
lv_obj_t *ui_tcda;
void ui_event_tob( lv_event_t * e);
lv_obj_t *ui_tob;
lv_obj_t *ui_tta;
lv_obj_t *ui_tattvd;
lv_obj_t *ui_tmainvd;
lv_obj_t *ui_tmainof;
lv_obj_t *ui_taxof;
void ui_event_tscd( lv_event_t * e);
lv_obj_t *ui_tscd;
lv_obj_t *ui_tvda;
void ui_event_tscdb( lv_event_t * e);
lv_obj_t *ui_tscdb;
void ui_event_tscib( lv_event_t * e);
lv_obj_t *ui_tscib;
lv_obj_t *ui_Label29;
lv_obj_t *ui_Label30;
lv_obj_t *ui_Label28;
lv_obj_t *ui_Label31;
lv_obj_t *ui_Label32;
lv_obj_t *ui_Label33;
lv_obj_t *ui_Label34;
lv_obj_t *ui_Label35;
lv_obj_t *ui_Label36;
lv_obj_t *ui_Label41;
lv_obj_t *ui_tovda;
lv_obj_t *ui_Label45;
lv_obj_t *ui_Label46;
lv_obj_t *ui_Spinner1;
lv_obj_t *ui_Checkbox9;
// CUSTOM VARIABLES


// SCREEN: ui_Screen8
void ui_Screen8_screen_init(void);
lv_obj_t *ui_Screen8;
lv_obj_t *ui_dtcd;
void ui_event_Button20( lv_event_t * e);
lv_obj_t *ui_Button20;
void ui_event_Button21( lv_event_t * e);
lv_obj_t *ui_Button21;
lv_obj_t *ui_did;
void ui_event_dsb( lv_event_t * e);
lv_obj_t *ui_dsb;
void ui_event_dcb( lv_event_t * e);
lv_obj_t *ui_dcb;
lv_obj_t *ui_Label38;
lv_obj_t *ui_Label39;
lv_obj_t *ui_Label40;
void ui_event_rdacb( lv_event_t * e);
lv_obj_t *ui_rdacb;
void ui_event_rurcb2( lv_event_t * e);
lv_obj_t *ui_rurcb2;
lv_obj_t *ui_Label53;
lv_obj_t *ui_Label54;
// CUSTOM VARIABLES


// SCREEN: ui_Screen9
void ui_Screen9_screen_init(void);
lv_obj_t *ui_Screen9;
lv_obj_t *ui_Label6;
void ui_event_Button24( lv_event_t * e);
lv_obj_t *ui_Button24;
void ui_event_Button25( lv_event_t * e);
lv_obj_t *ui_Button25;
// CUSTOM VARIABLES


// SCREEN: ui_Screen10
void ui_Screen10_screen_init(void);
lv_obj_t *ui_Screen10;
void ui_event_Button27( lv_event_t * e);
lv_obj_t *ui_Button27;
lv_obj_t *ui_Image4;
lv_obj_t *ui_Label7;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t *ui_imgset_[3] = {&ui_img_1_png, &ui_img_3_png, &ui_img_5_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_mccb( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      mccb_event( e );
}
}

void ui_event_rccb( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      rccb_event( e );
}
}

void ui_event_pccb( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      pccb_event( e );
}
}

void ui_event_pqcb( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      pqcb_event( e );
}
}

void ui_event_pfcb( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      pfcb_event( e );
}
}

void ui_event_dbb( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      dbb_event( e );
}
}

void ui_event_sccb( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      sccb_event( e );
}
}

void ui_event_mbub( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      mbub_event( e );
}
}

void ui_event_dbub( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      dbub_event( e );
}
}

void ui_event_mpb( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      map_event( e );
}
}

void ui_event_rupb( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      rupb_event( e );
}
}

void ui_event_rdpb( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      rdpb_event( e );
}
}

void ui_event_dpb( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      dpb_event( e );
}
}

void ui_event_axrb( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_state_modify( ui_t2rb, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_t1rb, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      attob_event( e );
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      axrb_event( e );
}
}

void ui_event_t1rb( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_state_modify( ui_axrb, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_t2rb, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      t1rb_event( e );
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      attob_event( e );
}
}

void ui_event_t2rb( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_state_modify( ui_t1rb, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_axrb, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      t2rb_event( e );
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      attob_event( e );
}
}

void ui_event_mainrb( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      mainrb_event( e );
}
}

void ui_event_rdarb( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      rdarb_event( e );
}
}

void ui_event_msvd( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      msvd_event( e );
}
}

void ui_event_mscd( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      mscd_event( e );
}
}

void ui_event_Button4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_spinbox_step( ui_msvd, -1);
}
}

void ui_event_Button5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_spinbox_step( ui_msvd, 1);
}
}

void ui_event_Button6( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_spinbox_step( ui_mscd, -1);
}
}

void ui_event_Button7( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_spinbox_step( ui_mscd, 1);
}
}

void ui_event_mpsob( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      mpsob_event( e );
}
}

void ui_event_Checkbox6( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_mpsob, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
}
if ( event_code == LV_EVENT_CLICKED) {
      mpsi_event( e );
}
}

void ui_event_mbb( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      mbb_event( e );
}
}

void ui_event_Button11( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_spinbox_step( ui_utcd, 1);
}
}

void ui_event_Button10( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_spinbox_step( ui_utcd, -1);
}
}

void ui_event_usb( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      usb_event( e );
}
}

void ui_event_ucb( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      ucb_event( e );
}
}

void ui_event_rurcb( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      rurcb_event( e );
}
}

void ui_event_rupcb( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      probe_event( e );
}
}

void ui_event_ossb( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      ossb_event( e );
}
}

void ui_event_oob( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      oob_event( e );
}
}

void ui_event_rub( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      rub_event( e );
}
}

void ui_event_tob( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      tob_event( e );
}
}

void ui_event_tscd( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      tscd_event( e );
}
}

void ui_event_tscdb( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_spinbox_step( ui_tscd, -1);
}
}

void ui_event_tscib( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_spinbox_step( ui_tscd, 1);
}
}

void ui_event_Button20( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_spinbox_step( ui_dtcd, 1);
}
}

void ui_event_Button21( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_spinbox_step( ui_dtcd, -1);
}
}

void ui_event_dsb( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      dsb_event( e );
}
}

void ui_event_dcb( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      dcb_event( e );
}
}

void ui_event_rdacb( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      rda_enb_event( e );
}
}

void ui_event_rurcb2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      rurcb_event( e );
}
}

void ui_event_Button24( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      confirm_yes( e );
}
}

void ui_event_Button25( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      confirm_no( e );
}
}

void ui_event_Button27( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      ResetOperation( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui_Screen2_screen_init();
ui_Screen3_screen_init();
ui_Screen4_screen_init();
ui_Screen5_screen_init();
ui_Screen6_screen_init();
ui_Screen7_screen_init();
ui_Screen8_screen_init();
ui_Screen9_screen_init();
ui_Screen10_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
