// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: MRI2

#ifndef _MRI2_UI_H
#define _MRI2_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_mbft;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t *ui_Screen2;
extern lv_obj_t *ui_Image3;
void ui_event_mccb( lv_event_t * e);
extern lv_obj_t *ui_mccb;
void ui_event_rccb( lv_event_t * e);
extern lv_obj_t *ui_rccb;
void ui_event_pccb( lv_event_t * e);
extern lv_obj_t *ui_pccb;
void ui_event_pqcb( lv_event_t * e);
extern lv_obj_t *ui_pqcb;
void ui_event_pfcb( lv_event_t * e);
extern lv_obj_t *ui_pfcb;
extern lv_obj_t *ui_dbta;
extern lv_obj_t *ui_Label48;
void ui_event_dbb( lv_event_t * e);
extern lv_obj_t *ui_dbb;
void ui_event_sccb( lv_event_t * e);
extern lv_obj_t *ui_sccb;
extern lv_obj_t *ui_Label44;
extern lv_obj_t *ui_Label47;
extern lv_obj_t *ui_Label49;
extern lv_obj_t *ui_Label50;
extern lv_obj_t *ui_Label51;
extern lv_obj_t *ui_Spinner2;
void ui_event_mbub( lv_event_t * e);
extern lv_obj_t *ui_mbub;
void ui_event_dbub( lv_event_t * e);
extern lv_obj_t *ui_dbub;
extern lv_obj_t *ui_Label52;
extern lv_obj_t *ui_Label55;
// CUSTOM VARIABLES

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t *ui_Screen3;
extern lv_obj_t *ui_Image2;
void ui_event_mpb( lv_event_t * e);
extern lv_obj_t *ui_mpb;
extern lv_obj_t *ui_Label2;
void ui_event_rupb( lv_event_t * e);
extern lv_obj_t *ui_rupb;
extern lv_obj_t *ui_Label3;
void ui_event_rdpb( lv_event_t * e);
extern lv_obj_t *ui_rdpb;
extern lv_obj_t *ui_Label4;
void ui_event_dpb( lv_event_t * e);
extern lv_obj_t *ui_dpb;
extern lv_obj_t *ui_Label1;
// CUSTOM VARIABLES

// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t *ui_Screen4;
void ui_event_axrb( lv_event_t * e);
extern lv_obj_t *ui_axrb;
void ui_event_t1rb( lv_event_t * e);
extern lv_obj_t *ui_t1rb;
void ui_event_t2rb( lv_event_t * e);
extern lv_obj_t *ui_t2rb;
void ui_event_mainrb( lv_event_t * e);
extern lv_obj_t *ui_mainrb;
void ui_event_rdarb( lv_event_t * e);
extern lv_obj_t *ui_rdarb;
extern lv_obj_t *ui_mvd;
extern lv_obj_t *ui_mcd;
void ui_event_msvd( lv_event_t * e);
extern lv_obj_t *ui_msvd;
void ui_event_mscd( lv_event_t * e);
extern lv_obj_t *ui_mscd;
void ui_event_Button4( lv_event_t * e);
extern lv_obj_t *ui_Button4;
void ui_event_Button5( lv_event_t * e);
extern lv_obj_t *ui_Button5;
void ui_event_Button6( lv_event_t * e);
extern lv_obj_t *ui_Button6;
void ui_event_Button7( lv_event_t * e);
extern lv_obj_t *ui_Button7;
void ui_event_mpsob( lv_event_t * e);
extern lv_obj_t *ui_mpsob;
void ui_event_Checkbox6( lv_event_t * e);
extern lv_obj_t *ui_Checkbox6;
void ui_event_mbb( lv_event_t * e);
extern lv_obj_t *ui_mbb;
extern lv_obj_t *ui_attvd;
extern lv_obj_t *ui_rdavd;
extern lv_obj_t *ui_mainvd;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_Label11;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui_Label13;
extern lv_obj_t *ui_Label14;
extern lv_obj_t *ui_Label15;
extern lv_obj_t *ui_Label16;
extern lv_obj_t *ui_Label17;
extern lv_obj_t *ui_Label43;
// CUSTOM VARIABLES

// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t *ui_Screen5;
extern lv_obj_t *ui_utcd;
void ui_event_Button11( lv_event_t * e);
extern lv_obj_t *ui_Button11;
void ui_event_Button10( lv_event_t * e);
extern lv_obj_t *ui_Button10;
extern lv_obj_t *ui_uid;
void ui_event_usb( lv_event_t * e);
extern lv_obj_t *ui_usb;
void ui_event_ucb( lv_event_t * e);
extern lv_obj_t *ui_ucb;
void ui_event_rurcb( lv_event_t * e);
extern lv_obj_t *ui_rurcb;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Label18;
extern lv_obj_t *ui_Label20;
extern lv_obj_t *ui_Label21;
extern lv_obj_t *ui_Label37;
void ui_event_rupcb( lv_event_t * e);
extern lv_obj_t *ui_rupcb;
extern lv_obj_t *ui_Label42;
extern lv_obj_t *ui_Spinner3;
extern lv_obj_t *ui_Checkbox7;
// CUSTOM VARIABLES

// SCREEN: ui_Screen6
void ui_Screen6_screen_init(void);
extern lv_obj_t *ui_Screen6;
extern lv_obj_t *ui_ocd;
extern lv_obj_t *ui_ovd;
extern lv_obj_t *ui_otd;
void ui_event_ossb( lv_event_t * e);
extern lv_obj_t *ui_ossb;
void ui_event_oob( lv_event_t * e);
extern lv_obj_t *ui_oob;
extern lv_obj_t *ui_opb;
extern lv_obj_t *ui_ota;
extern lv_obj_t *ui_oattvd;
extern lv_obj_t *ui_omainvd;
extern lv_obj_t *ui_mainof;
extern lv_obj_t *ui_axof;
extern lv_obj_t *ui_Label22;
extern lv_obj_t *ui_Label19;
extern lv_obj_t *ui_Label23;
extern lv_obj_t *ui_Label24;
extern lv_obj_t *ui_Label25;
extern lv_obj_t *ui_Label26;
extern lv_obj_t *ui_Label27;
void ui_event_rub( lv_event_t * e);
extern lv_obj_t *ui_rub;
extern lv_obj_t *ui_tovd;
// CUSTOM VARIABLES

// SCREEN: ui_Screen7
void ui_Screen7_screen_init(void);
extern lv_obj_t *ui_Screen7;
extern lv_obj_t *ui_tcda;
void ui_event_tob( lv_event_t * e);
extern lv_obj_t *ui_tob;
extern lv_obj_t *ui_tta;
extern lv_obj_t *ui_tattvd;
extern lv_obj_t *ui_tmainvd;
extern lv_obj_t *ui_tmainof;
extern lv_obj_t *ui_taxof;
void ui_event_tscd( lv_event_t * e);
extern lv_obj_t *ui_tscd;
extern lv_obj_t *ui_tvda;
void ui_event_tscdb( lv_event_t * e);
extern lv_obj_t *ui_tscdb;
void ui_event_tscib( lv_event_t * e);
extern lv_obj_t *ui_tscib;
extern lv_obj_t *ui_Label29;
extern lv_obj_t *ui_Label30;
extern lv_obj_t *ui_Label28;
extern lv_obj_t *ui_Label31;
extern lv_obj_t *ui_Label32;
extern lv_obj_t *ui_Label33;
extern lv_obj_t *ui_Label34;
extern lv_obj_t *ui_Label35;
extern lv_obj_t *ui_Label36;
extern lv_obj_t *ui_Label41;
extern lv_obj_t *ui_tovda;
extern lv_obj_t *ui_Label45;
extern lv_obj_t *ui_Label46;
extern lv_obj_t *ui_Spinner1;
extern lv_obj_t *ui_Checkbox9;
// CUSTOM VARIABLES

// SCREEN: ui_Screen8
void ui_Screen8_screen_init(void);
extern lv_obj_t *ui_Screen8;
extern lv_obj_t *ui_dtcd;
void ui_event_Button20( lv_event_t * e);
extern lv_obj_t *ui_Button20;
void ui_event_Button21( lv_event_t * e);
extern lv_obj_t *ui_Button21;
extern lv_obj_t *ui_did;
void ui_event_dsb( lv_event_t * e);
extern lv_obj_t *ui_dsb;
void ui_event_dcb( lv_event_t * e);
extern lv_obj_t *ui_dcb;
extern lv_obj_t *ui_Label38;
extern lv_obj_t *ui_Label39;
extern lv_obj_t *ui_Label40;
void ui_event_rdacb( lv_event_t * e);
extern lv_obj_t *ui_rdacb;
void ui_event_rurcb2( lv_event_t * e);
extern lv_obj_t *ui_rurcb2;
extern lv_obj_t *ui_Label53;
extern lv_obj_t *ui_Label54;
// CUSTOM VARIABLES

// SCREEN: ui_Screen9
void ui_Screen9_screen_init(void);
extern lv_obj_t *ui_Screen9;
extern lv_obj_t *ui_Label6;
void ui_event_Button24( lv_event_t * e);
extern lv_obj_t *ui_Button24;
void ui_event_Button25( lv_event_t * e);
extern lv_obj_t *ui_Button25;
// CUSTOM VARIABLES

// SCREEN: ui_Screen10
void ui_Screen10_screen_init(void);
extern lv_obj_t *ui_Screen10;
void ui_event_Button27( lv_event_t * e);
extern lv_obj_t *ui_Button27;
extern lv_obj_t *ui_Image4;
extern lv_obj_t *ui_Label7;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_1_png);   // assets/1.png
LV_IMG_DECLARE( ui_img_diag_png);   // assets/diag.png
LV_IMG_DECLARE( ui_img_back_png);   // assets/back.png
LV_IMG_DECLARE( ui_img_3_png);   // assets/3.png
LV_IMG_DECLARE( ui_img_next_png);   // assets/next.png
LV_IMG_DECLARE( ui_img_play_stop_png);   // assets/play_stop.png
LV_IMG_DECLARE( ui_img_2088487156);   // assets/tik-removebg-preview.png
LV_IMG_DECLARE( ui_img_cancel_png);   // assets/cancel.png
LV_IMG_DECLARE( ui_img_25948186);   // assets/attention-removebg-preview.png
LV_IMG_DECLARE( ui_img_5_png);   // assets/5.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
