// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: MRI2

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void mccb_event(lv_event_t * e);
void rccb_event(lv_event_t * e);
void pccb_event(lv_event_t * e);
void pqcb_event(lv_event_t * e);
void pfcb_event(lv_event_t * e);
void dbb_event(lv_event_t * e);
void sccb_event(lv_event_t * e);
void mbub_event(lv_event_t * e);
void dbub_event(lv_event_t * e);
void map_event(lv_event_t * e);
void rupb_event(lv_event_t * e);
void rdpb_event(lv_event_t * e);
void dpb_event(lv_event_t * e);
void attob_event(lv_event_t * e);
void axrb_event(lv_event_t * e);
void t1rb_event(lv_event_t * e);
void t2rb_event(lv_event_t * e);
void mainrb_event(lv_event_t * e);
void rdarb_event(lv_event_t * e);
void msvd_event(lv_event_t * e);
void mscd_event(lv_event_t * e);
void mpsob_event(lv_event_t * e);
void mpsi_event(lv_event_t * e);
void mbb_event(lv_event_t * e);
void usb_event(lv_event_t * e);
void ucb_event(lv_event_t * e);
void rurcb_event(lv_event_t * e);
void probe_event(lv_event_t * e);
void ossb_event(lv_event_t * e);
void oob_event(lv_event_t * e);
void rub_event(lv_event_t * e);
void tob_event(lv_event_t * e);
void tscd_event(lv_event_t * e);
void dsb_event(lv_event_t * e);
void dcb_event(lv_event_t * e);
void rda_enb_event(lv_event_t * e);
void confirm_yes(lv_event_t * e);
void confirm_no(lv_event_t * e);
void ResetOperation(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
