// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: MRI2

#include "../ui.h"

void ui_Screen5_screen_init(void)
{
ui_Screen5 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen5, lv_color_hex(0xE6F2F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_utcd = lv_spinbox_create(ui_Screen5);
lv_obj_set_width( ui_utcd, 190);
lv_obj_set_height( ui_utcd, 76);
lv_obj_set_x( ui_utcd, -232 );
lv_obj_set_y( ui_utcd, -100 );
lv_obj_set_align( ui_utcd, LV_ALIGN_CENTER );
lv_spinbox_set_digit_format( ui_utcd, 5, 3);
lv_spinbox_set_range( ui_utcd, 0,99999 );
lv_spinbox_set_cursor_pos(ui_utcd, 1 - 1);
lv_spinbox_set_value( ui_utcd, 100 );
lv_obj_set_style_text_font(ui_utcd, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button11 = lv_btn_create(ui_Screen5);
lv_obj_set_width( ui_Button11, 70);
lv_obj_set_height( ui_Button11, 70);
lv_obj_set_x( ui_Button11, -175 );
lv_obj_set_y( ui_Button11, -5 );
lv_obj_set_align( ui_Button11, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button11, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button11, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Button11, 80, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button10 = lv_btn_create(ui_Screen5);
lv_obj_set_width( ui_Button10, 70);
lv_obj_set_height( ui_Button10, 70);
lv_obj_set_x( ui_Button10, -288 );
lv_obj_set_y( ui_Button10, -5 );
lv_obj_set_align( ui_Button10, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button10, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Button10, 80, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uid = lv_dropdown_create(ui_Screen5);
lv_dropdown_set_options( ui_uid, "500mA\n600mA\n700mA\n800mA\n900mA\n1A\n1.5A\n2A\n2.5A\n3A\n5A\n10A" );
lv_obj_set_width( ui_uid, 150);
lv_obj_set_height( ui_uid, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_uid, 35 );
lv_obj_set_y( ui_uid, -115 );
lv_obj_set_align( ui_uid, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_uid, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags



ui_usb = lv_btn_create(ui_Screen5);
lv_obj_set_width( ui_usb, 100);
lv_obj_set_height( ui_usb, 97);
lv_obj_set_x( ui_usb, 303 );
lv_obj_set_y( ui_usb, -10 );
lv_obj_set_align( ui_usb, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_usb, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_usb, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_usb, lv_color_hex(0x32C670), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_usb, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_usb, &ui_img_next_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_img_recolor(ui_usb, lv_color_hex(0x414041), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_recolor_opa(ui_usb, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ucb = lv_btn_create(ui_Screen5);
lv_obj_set_width( ui_ucb, 70);
lv_obj_set_height( ui_ucb, 70);
lv_obj_set_x( ui_ucb, -355 );
lv_obj_set_y( ui_ucb, 195 );
lv_obj_set_align( ui_ucb, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ucb, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ucb, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ucb, 35, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ucb, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ucb, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_ucb, &ui_img_back_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_img_recolor(ui_ucb, lv_color_hex(0xE6F2F6), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_recolor_opa(ui_ucb, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_rurcb = lv_btn_create(ui_Screen5);
lv_obj_set_width( ui_rurcb, 176);
lv_obj_set_height( ui_rurcb, 88);
lv_obj_set_x( ui_rurcb, -145 );
lv_obj_set_y( ui_rurcb, 144 );
lv_obj_set_align( ui_rurcb, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_rurcb, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_rurcb, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_rurcb, lv_color_hex(0xAE8125), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_rurcb, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label5 = lv_label_create(ui_Screen5);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, -145 );
lv_obj_set_y( ui_Label5, 145 );
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"Read Ramp\n    Current");
lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label18 = lv_label_create(ui_Screen5);
lv_obj_set_width( ui_Label18, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label18, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label18, -87 );
lv_obj_set_y( ui_Label18, -150 );
lv_obj_set_align( ui_Label18, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label18,"Target Current                                  Increasing Current");
lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label20 = lv_label_create(ui_Screen5);
lv_obj_set_width( ui_Label20, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label20, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label20, -2 );
lv_obj_set_y( ui_Label20, -218 );
lv_obj_set_align( ui_Label20, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label20,"                                              Ramp Up Settings                                               ");
lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0xE6F2F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Label20, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Label20, lv_color_hex(0x31C673), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Label20, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label21 = lv_label_create(ui_Screen5);
lv_obj_set_width( ui_Label21, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label21, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label21, -229 );
lv_obj_set_y( ui_Label21, -7 );
lv_obj_set_align( ui_Label21, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label21,"-       +");
lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0xE6F2F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label21, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label21, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label37 = lv_label_create(ui_Screen5);
lv_obj_set_width( ui_Label37, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label37, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label37, -148 );
lv_obj_set_y( ui_Label37, 210 );
lv_obj_set_align( ui_Label37, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label37,"Reads from magnet, only for Philips.");

ui_rupcb = lv_btn_create(ui_Screen5);
lv_obj_set_width( ui_rupcb, 176);
lv_obj_set_height( ui_rupcb, 88);
lv_obj_set_x( ui_rupcb, 169 );
lv_obj_set_y( ui_rupcb, 144 );
lv_obj_set_align( ui_rupcb, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_rupcb, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_rupcb, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_rupcb, lv_color_hex(0xE1BA15), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_rupcb, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label42 = lv_label_create(ui_Screen5);
lv_obj_set_width( ui_Label42, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label42, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label42, 170 );
lv_obj_set_y( ui_Label42, 144 );
lv_obj_set_align( ui_Label42, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label42,"Probe \nCheck");
lv_obj_set_style_text_font(ui_Label42, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Spinner3 = lv_spinner_create(ui_Screen5,1000,90);
lv_obj_set_width( ui_Spinner3, 80);
lv_obj_set_height( ui_Spinner3, 80);
lv_obj_set_x( ui_Spinner3, 328 );
lv_obj_set_y( ui_Spinner3, 146 );
lv_obj_set_align( ui_Spinner3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Spinner3, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_Spinner3, LV_OBJ_FLAG_CLICKABLE );    /// Flags

ui_Checkbox7 = lv_checkbox_create(ui_Screen5);
lv_checkbox_set_text(ui_Checkbox7,"");
lv_obj_set_width( ui_Checkbox7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Checkbox7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Checkbox7, 333 );
lv_obj_set_y( ui_Checkbox7, 147 );
lv_obj_set_align( ui_Checkbox7, LV_ALIGN_CENTER );
lv_obj_add_state( ui_Checkbox7, LV_STATE_CHECKED | LV_STATE_DISABLED );     /// States
lv_obj_add_flag( ui_Checkbox7, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_font(ui_Checkbox7, &lv_font_montserrat_46, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Checkbox7, lv_color_hex(0x2DD525), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_Checkbox7, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);

lv_obj_add_event_cb(ui_Button11, ui_event_Button11, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button10, ui_event_Button10, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_usb, ui_event_usb, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ucb, ui_event_ucb, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_rurcb, ui_event_rurcb, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_rupcb, ui_event_rupcb, LV_EVENT_ALL, NULL);

}
