// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: MRI2

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0xE6F2F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Image3, &ui_img_diag_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_mccb = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_mccb, 189);
    lv_obj_set_height(ui_mccb, 50);
    lv_obj_set_x(ui_mccb, -256);
    lv_obj_set_y(ui_mccb, -64);
    lv_obj_set_align(ui_mccb, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mccb, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_mccb, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_mccb, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mccb, lv_color_hex(0xE5E5EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mccb, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rccb = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_rccb, 189);
    lv_obj_set_height(ui_rccb, 50);
    lv_obj_set_x(ui_rccb, -258);
    lv_obj_set_y(ui_rccb, 28);
    lv_obj_set_align(ui_rccb, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rccb, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_rccb, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_rccb, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rccb, lv_color_hex(0xE5E5EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rccb, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pccb = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_pccb, 189);
    lv_obj_set_height(ui_pccb, 50);
    lv_obj_set_x(ui_pccb, -256);
    lv_obj_set_y(ui_pccb, 119);
    lv_obj_set_align(ui_pccb, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pccb, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_pccb, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pccb, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pccb, lv_color_hex(0xE5E5EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pccb, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pqcb = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_pqcb, 189);
    lv_obj_set_height(ui_pqcb, 50);
    lv_obj_set_x(ui_pqcb, 5);
    lv_obj_set_y(ui_pqcb, 119);
    lv_obj_set_align(ui_pqcb, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pqcb, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_pqcb, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pqcb, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pqcb, lv_color_hex(0xE5E5EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pqcb, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pfcb = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_pfcb, 189);
    lv_obj_set_height(ui_pfcb, 50);
    lv_obj_set_x(ui_pfcb, 267);
    lv_obj_set_y(ui_pfcb, 118);
    lv_obj_set_align(ui_pfcb, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pfcb, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_pfcb, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pfcb, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pfcb, lv_color_hex(0xE5E5EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pfcb, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dbta = lv_textarea_create(ui_Screen2);
    lv_obj_set_width(ui_dbta, 461);
    lv_obj_set_height(ui_dbta, 249);
    lv_obj_set_x(ui_dbta, 122);
    lv_obj_set_y(ui_dbta, -73);
    lv_obj_set_align(ui_dbta, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_dbta, "Placeholder...");
    lv_obj_set_style_text_font(ui_dbta, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Label48 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label48, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label48, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label48, -2);
    lv_obj_set_y(ui_Label48, -218);
    lv_obj_set_align(ui_Label48, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label48,
                      "                                                      Diagnostics                                                    ");
    lv_obj_set_style_text_color(ui_Label48, lv_color_hex(0xE6F2F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label48, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label48, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label48, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label48, lv_color_hex(0x31C673), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label48, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dbb = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_dbb, 70);
    lv_obj_set_height(ui_dbb, 70);
    lv_obj_set_x(ui_dbb, -355);
    lv_obj_set_y(ui_dbb, 195);
    lv_obj_set_align(ui_dbb, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dbb, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_dbb, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dbb, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dbb, lv_color_hex(0x414141), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dbb, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_dbb, &ui_img_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_dbb, lv_color_hex(0xE6F2F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_dbb, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sccb = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_sccb, 189);
    lv_obj_set_height(ui_sccb, 50);
    lv_obj_set_x(ui_sccb, -257);
    lv_obj_set_y(ui_sccb, -156);
    lv_obj_set_align(ui_sccb, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sccb, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_sccb, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_sccb, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_sccb, lv_color_hex(0xE5E5EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sccb, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label44 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label44, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label44, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label44, 60);
    lv_obj_set_y(ui_Label44, 76);
    lv_label_set_text(ui_Label44, " Shim Control Check\n Main Control Check\n RDA Control Check");
    lv_obj_set_style_text_letter_space(ui_Label44, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label44, 74, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label44, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label47 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label47, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label47, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label47, 60);
    lv_obj_set_y(ui_Label47, 342);
    lv_label_set_text(ui_Label47, "PSU Communication \n               Check");
    lv_obj_set_style_text_font(ui_Label47, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label49 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label49, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label49, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label49, 331);
    lv_obj_set_y(ui_Label49, 351);
    lv_label_set_text(ui_Label49, "PSU  Quick Check");
    lv_obj_set_style_text_font(ui_Label49, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label50 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label50, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label50, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label50, 575);
    lv_obj_set_y(ui_Label50, 347);
    lv_label_set_text(ui_Label50, "PSU  Functional Check");
    lv_obj_set_style_text_letter_space(ui_Label50, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label50, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label50, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label51 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label51, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label51, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label51, 591);
    lv_obj_set_y(ui_Label51, 364);
    lv_label_set_text(ui_Label51, "(Output must be shorted)");
    lv_obj_set_style_text_letter_space(ui_Label51, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label51, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label51, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner2 = lv_spinner_create(ui_Screen2, 1000, 90);
    lv_obj_set_width(ui_Spinner2, 49);
    lv_obj_set_height(ui_Spinner2, 46);
    lv_obj_set_x(ui_Spinner2, 323);
    lv_obj_set_y(ui_Spinner2, 26);
    lv_obj_set_align(ui_Spinner2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Spinner2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Spinner2, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_mbub = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_mbub, 145);
    lv_obj_set_height(ui_mbub, 42);
    lv_obj_set_x(ui_mbub, -126);
    lv_obj_set_y(ui_mbub, 203);
    lv_obj_set_align(ui_mbub, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mbub, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_mbub, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_mbub, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mbub, lv_color_hex(0xE5E5EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mbub, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dbub = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_dbub, 145);
    lv_obj_set_height(ui_dbub, 42);
    lv_obj_set_x(ui_dbub, 133);
    lv_obj_set_y(ui_dbub, 203);
    lv_obj_set_align(ui_dbub, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dbub, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_dbub, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dbub, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dbub, lv_color_hex(0xE5E5EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dbub, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label52 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label52, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label52, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label52, -127);
    lv_obj_set_y(ui_Label52, 204);
    lv_obj_set_align(ui_Label52, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label52, "Update Display");

    ui_Label55 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label55, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label55, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label55, 135);
    lv_obj_set_y(ui_Label55, 204);
    lv_obj_set_align(ui_Label55, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label55, "Update M. Board");

    lv_obj_add_event_cb(ui_mccb, ui_event_mccb, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_rccb, ui_event_rccb, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pccb, ui_event_pccb, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pqcb, ui_event_pqcb, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pfcb, ui_event_pfcb, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_dbb, ui_event_dbb, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sccb, ui_event_sccb, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_mbub, ui_event_mbub, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_dbub, ui_event_dbub, LV_EVENT_ALL, NULL);

}
