// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: MRI2

#include "../ui.h"

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen4, lv_color_hex(0xE6F2F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_axrb = lv_switch_create(ui_Screen4);
    lv_obj_set_width(ui_axrb, 90);
    lv_obj_set_height(ui_axrb, 43);
    lv_obj_set_x(ui_axrb, 207);
    lv_obj_set_y(ui_axrb, -165);
    lv_obj_set_align(ui_axrb, LV_ALIGN_CENTER);


    ui_t1rb = lv_switch_create(ui_Screen4);
    lv_obj_set_width(ui_t1rb, 90);
    lv_obj_set_height(ui_t1rb, 43);
    lv_obj_set_x(ui_t1rb, 207);
    lv_obj_set_y(ui_t1rb, -110);
    lv_obj_set_align(ui_t1rb, LV_ALIGN_CENTER);


    ui_t2rb = lv_switch_create(ui_Screen4);
    lv_obj_set_width(ui_t2rb, 90);
    lv_obj_set_height(ui_t2rb, 43);
    lv_obj_set_x(ui_t2rb, 207);
    lv_obj_set_y(ui_t2rb, -55);
    lv_obj_set_align(ui_t2rb, LV_ALIGN_CENTER);


    ui_mainrb = lv_switch_create(ui_Screen4);
    lv_obj_set_width(ui_mainrb, 90);
    lv_obj_set_height(ui_mainrb, 43);
    lv_obj_set_x(ui_mainrb, 207);
    lv_obj_set_y(ui_mainrb, 32);
    lv_obj_set_align(ui_mainrb, LV_ALIGN_CENTER);


    ui_rdarb = lv_switch_create(ui_Screen4);
    lv_obj_set_width(ui_rdarb, 90);
    lv_obj_set_height(ui_rdarb, 43);
    lv_obj_set_x(ui_rdarb, 207);
    lv_obj_set_y(ui_rdarb, 162);
    lv_obj_set_align(ui_rdarb, LV_ALIGN_CENTER);


    ui_mvd = lv_spinbox_create(ui_Screen4);
    lv_obj_set_width(ui_mvd, 150);
    lv_obj_set_height(ui_mvd, 66);
    lv_obj_set_x(ui_mvd, -269);
    lv_obj_set_y(ui_mvd, -139);
    lv_obj_set_align(ui_mvd, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_mvd, 5, 3);
    lv_spinbox_set_range(ui_mvd, 0, 99999);
    lv_spinbox_set_cursor_pos(ui_mvd, 1 - 1);
    lv_obj_set_style_text_font(ui_mvd, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_mvd, lv_color_hex(0xFFFFFF), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mvd, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_mvd, lv_color_hex(0x202020), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mvd, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_mcd = lv_spinbox_create(ui_Screen4);
    lv_obj_set_width(ui_mcd, 150);
    lv_obj_set_height(ui_mcd, 66);
    lv_obj_set_x(ui_mcd, -79);
    lv_obj_set_y(ui_mcd, -139);
    lv_obj_set_align(ui_mcd, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_mcd, 5, 3);
    lv_spinbox_set_range(ui_mcd, 0, 99999);
    lv_spinbox_set_cursor_pos(ui_mcd, 1 - 1);
    lv_obj_set_style_text_font(ui_mcd, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_mcd, lv_color_hex(0xFFFFFF), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mcd, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_mcd, lv_color_hex(0x202020), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mcd, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_msvd = lv_spinbox_create(ui_Screen4);
    lv_obj_set_width(ui_msvd, 190);
    lv_obj_set_height(ui_msvd, 76);
    lv_obj_set_x(ui_msvd, -288);
    lv_obj_set_y(ui_msvd, -54);
    lv_obj_set_align(ui_msvd, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_msvd, 5, 3);
    lv_spinbox_set_range(ui_msvd, 0, 99999);
    lv_spinbox_set_cursor_pos(ui_msvd, 1 - 1);
    lv_obj_set_style_text_font(ui_msvd, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mscd = lv_spinbox_create(ui_Screen4);
    lv_obj_set_width(ui_mscd, 190);
    lv_obj_set_height(ui_mscd, 76);
    lv_obj_set_x(ui_mscd, -58);
    lv_obj_set_y(ui_mscd, -54);
    lv_obj_set_align(ui_mscd, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_mscd, 5, 3);
    lv_spinbox_set_range(ui_mscd, 0, 99999);
    lv_spinbox_set_cursor_pos(ui_mscd, 1 - 1);
    lv_obj_set_style_text_font(ui_mscd, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button4, 70);
    lv_obj_set_height(ui_Button4, 70);
    lv_obj_set_x(ui_Button4, -347);
    lv_obj_set_y(ui_Button4, 40);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button4, 80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button5, 70);
    lv_obj_set_height(ui_Button5, 70);
    lv_obj_set_x(ui_Button5, -233);
    lv_obj_set_y(ui_Button5, 38);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button5, 80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button6 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button6, 70);
    lv_obj_set_height(ui_Button6, 70);
    lv_obj_set_x(ui_Button6, -117);
    lv_obj_set_y(ui_Button6, 40);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button6, 80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button7 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button7, 70);
    lv_obj_set_height(ui_Button7, 70);
    lv_obj_set_x(ui_Button7, -3);
    lv_obj_set_y(ui_Button7, 39);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button7, 80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mpsob = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_mpsob, 80);
    lv_obj_set_height(ui_mpsob, 80);
    lv_obj_set_x(ui_mpsob, -169);
    lv_obj_set_y(ui_mpsob, 136);
    lv_obj_set_align(ui_mpsob, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mpsob, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_mpsob, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_mpsob, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mpsob, lv_color_hex(0x32C670), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mpsob, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Checkbox6 = lv_checkbox_create(ui_Screen4);
    lv_checkbox_set_text(ui_Checkbox6, "Instant");
    lv_obj_set_width(ui_Checkbox6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Checkbox6, -168);
    lv_obj_set_y(ui_Checkbox6, 212);
    lv_obj_set_align(ui_Checkbox6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Checkbox6, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Checkbox6, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Checkbox6, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_mbb = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_mbb, 70);
    lv_obj_set_height(ui_mbb, 70);
    lv_obj_set_x(ui_mbb, -355);
    lv_obj_set_y(ui_mbb, 195);
    lv_obj_set_align(ui_mbb, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mbb, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_mbb, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_mbb, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mbb, lv_color_hex(0x414141), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mbb, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_mbb, &ui_img_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_mbb, lv_color_hex(0xE6F2F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_mbb, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_attvd = lv_spinbox_create(ui_Screen4);
    lv_obj_set_width(ui_attvd, 80);
    lv_obj_set_height(ui_attvd, 53);
    lv_obj_set_x(ui_attvd, 320);
    lv_obj_set_y(ui_attvd, -142);
    lv_obj_set_align(ui_attvd, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_attvd, 3, 2);
    lv_spinbox_set_range(ui_attvd, 0, 999);
    lv_spinbox_set_cursor_pos(ui_attvd, 1 - 1);
    lv_obj_set_style_text_font(ui_attvd, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_attvd, lv_color_hex(0xFFFFFF), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_attvd, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_attvd, lv_color_hex(0x232423), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_attvd, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_attvd, &lv_font_montserrat_28, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_rdavd = lv_spinbox_create(ui_Screen4);
    lv_obj_set_width(ui_rdavd, 80);
    lv_obj_set_height(ui_rdavd, 53);
    lv_obj_set_x(ui_rdavd, 320);
    lv_obj_set_y(ui_rdavd, 162);
    lv_obj_set_align(ui_rdavd, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_rdavd, 3, 2);
    lv_spinbox_set_range(ui_rdavd, 0, 999);
    lv_spinbox_set_cursor_pos(ui_rdavd, 1 - 1);
    lv_obj_set_style_text_font(ui_rdavd, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_rdavd, lv_color_hex(0xFFFFFF), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rdavd, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_rdavd, lv_color_hex(0x232423), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rdavd, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rdavd, &lv_font_montserrat_28, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_mainvd = lv_spinbox_create(ui_Screen4);
    lv_obj_set_width(ui_mainvd, 80);
    lv_obj_set_height(ui_mainvd, 53);
    lv_obj_set_x(ui_mainvd, 320);
    lv_obj_set_y(ui_mainvd, 32);
    lv_obj_set_align(ui_mainvd, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_mainvd, 3, 2);
    lv_spinbox_set_range(ui_mainvd, 0, 999);
    lv_spinbox_set_cursor_pos(ui_mainvd, 1 - 1);
    lv_obj_set_style_text_font(ui_mainvd, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_mainvd, lv_color_hex(0xFFFFFF), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainvd, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_mainvd, lv_color_hex(0x232423), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mainvd, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mainvd, &lv_font_montserrat_28, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -58);
    lv_obj_set_y(ui_Label8, 38);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "-       +");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xE6F2F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -288);
    lv_obj_set_y(ui_Label9, 38);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "-       +");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xE6F2F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -169);
    lv_obj_set_y(ui_Label10, 135);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "OK");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xE6F2F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 130);
    lv_obj_set_y(ui_Label11, -109);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "AX\n T1\n T2");
    lv_obj_set_style_text_letter_space(ui_Label11, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label11, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 373);
    lv_obj_set_y(ui_Label12, -140);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "V");
    lv_obj_set_style_text_letter_space(ui_Label12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label12, 28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -174);
    lv_obj_set_y(ui_Label13, -138);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "V A");
    lv_obj_set_style_text_letter_space(ui_Label13, 170, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 120);
    lv_obj_set_y(ui_Label14, 99);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Main\n RDA");
    lv_obj_set_style_text_letter_space(ui_Label14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label14, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -2);
    lv_obj_set_y(ui_Label15, -218);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15,
                      "               Ramp Coil Control                                          Shim Control         ");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0xE6F2F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label15, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label15, lv_color_hex(0x31C673), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 373);
    lv_obj_set_y(ui_Label16, 166);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "V");
    lv_obj_set_style_text_letter_space(ui_Label16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label16, 28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, 373);
    lv_obj_set_y(ui_Label17, 36);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "V");
    lv_obj_set_style_text_letter_space(ui_Label17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label17, 28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label43 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label43, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label43, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label43, 71);
    lv_obj_set_y(ui_Label43, 45);
    lv_label_set_text(ui_Label43, "Actual Voltage                  Actual Current");
    lv_obj_set_style_text_font(ui_Label43, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_axrb, ui_event_axrb, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_t1rb, ui_event_t1rb, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_t2rb, ui_event_t2rb, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_mainrb, ui_event_mainrb, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_rdarb, ui_event_rdarb, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_msvd, ui_event_msvd, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_mscd, ui_event_mscd, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_mpsob, ui_event_mpsob, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Checkbox6, ui_event_Checkbox6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_mbb, ui_event_mbb, LV_EVENT_ALL, NULL);

}
