// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: MRI3

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image1 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image1, &ui_img_1_png);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image1, -1 );
lv_obj_set_y( ui_Image1, 0 );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_pivot(ui_Image1,403,225);

ui_mbft = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_mbft, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mbft, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_mbft, 1 );
lv_obj_set_y( ui_mbft, 195 );
lv_obj_set_align( ui_mbft, LV_ALIGN_CENTER );
lv_label_set_text(ui_mbft,"* Main Board Communiaction Fail! *");
lv_obj_add_flag( ui_mbft, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_text_color(ui_mbft, lv_color_hex(0xE71212), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_mbft, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_mbft, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label58 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label58, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label58, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label58, 250 );
lv_obj_set_y( ui_Label58, 92 );
lv_obj_set_align( ui_Label58, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label58,"Screen Version : 1.2\nBoard Version   : 1.2");
lv_obj_set_style_text_font(ui_Label58, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_splash = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_splash, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_splash, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_splash, 2 );
lv_obj_set_y( ui_splash, 216 );
lv_obj_set_align( ui_splash, LV_ALIGN_CENTER );
lv_label_set_text(ui_splash,"MPSONE UNIVERSAL MPS SYSTEM");
lv_obj_set_style_text_color(ui_splash, lv_color_hex(0x393031), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_splash, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_splash, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);


}
