// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: MRI3

#include "../ui.h"

void ui_Screen10_screen_init(void)
{
ui_Screen10 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen10, lv_color_hex(0xE6F2F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Chart1 = lv_chart_create(ui_Screen10);
lv_obj_set_width( ui_Chart1, 671);
lv_obj_set_height( ui_Chart1, 336);
lv_obj_set_x( ui_Chart1, 3 );
lv_obj_set_y( ui_Chart1, -49 );
lv_obj_set_align( ui_Chart1, LV_ALIGN_CENTER );
lv_chart_set_type( ui_Chart1, LV_CHART_TYPE_LINE);
lv_chart_set_range( ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 0, 800);
lv_chart_set_range( ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 0, 800);
lv_chart_set_axis_tick( ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 4, 5, 11, 2, true, 50);
lv_chart_set_axis_tick( ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
lv_chart_set_axis_tick( ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
lv_chart_series_t* ui_Chart1_series_1 = lv_chart_add_series(ui_Chart1, lv_color_hex(0x808080), LV_CHART_AXIS_PRIMARY_Y);
static lv_coord_t ui_Chart1_series_1_array[] = { 10,20,30,40,50,60,70,80,90,100,120 };
lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_1, ui_Chart1_series_1_array);



ui_gbb = lv_btn_create(ui_Screen10);
lv_obj_set_width( ui_gbb, 70);
lv_obj_set_height( ui_gbb, 70);
lv_obj_set_x( ui_gbb, -355 );
lv_obj_set_y( ui_gbb, 195 );
lv_obj_set_align( ui_gbb, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_gbb, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_gbb, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_gbb, 80, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_gbb, lv_color_hex(0x414141), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_gbb, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_gbb, &ui_img_back_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_img_recolor(ui_gbb, lv_color_hex(0xE6F2F6), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_recolor_opa(ui_gbb, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Dropdown1 = lv_dropdown_create(ui_Screen10);
lv_dropdown_set_options( ui_Dropdown1, "Ramp Up 1\nRamp Up 2\nRamp Up 3" );
lv_obj_set_width( ui_Dropdown1, 213);
lv_obj_set_height( ui_Dropdown1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Dropdown1, -158 );
lv_obj_set_y( ui_Dropdown1, 191 );
lv_obj_set_align( ui_Dropdown1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags



ui_dlt = lv_btn_create(ui_Screen10);
lv_obj_set_width( ui_dlt, 146);
lv_obj_set_height( ui_dlt, 50);
lv_obj_set_x( ui_dlt, 231 );
lv_obj_set_y( ui_dlt, 188 );
lv_obj_set_align( ui_dlt, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_dlt, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_dlt, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_dlt, lv_color_hex(0xA02D2D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_dlt, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Spinner4 = lv_spinner_create(ui_Screen10,1000,90);
lv_obj_set_width( ui_Spinner4, 48);
lv_obj_set_height( ui_Spinner4, 53);
lv_obj_set_x( ui_Spinner4, 354 );
lv_obj_set_y( ui_Spinner4, 195 );
lv_obj_set_align( ui_Spinner4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Spinner4, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_Spinner4, LV_OBJ_FLAG_CLICKABLE );    /// Flags

ui_dlt1 = lv_btn_create(ui_Screen10);
lv_obj_set_width( ui_dlt1, 146);
lv_obj_set_height( ui_dlt1, 50);
lv_obj_set_x( ui_dlt1, 65 );
lv_obj_set_y( ui_dlt1, 189 );
lv_obj_set_align( ui_dlt1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_dlt1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_dlt1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_dlt1, lv_color_hex(0x2DA02D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_dlt1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_gbb, ui_event_gbb, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Dropdown1, ui_event_Dropdown1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_dlt, ui_event_dlt, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_dlt1, ui_event_dlt1, LV_EVENT_ALL, NULL);

}
